### ISSUE TITLE
Project upload does not always work

### ISSUE THREAD

**Issue by rsgoncalves** [protegeproject/protege-ontology-client#27]
Logged in as root, I created a new project using the Add Project dialog, and pressed Ok. It immediately appeared in the list of Projects in the Admin UI. I then pressed the "Save" button in the 'JSON Serialization' view, but the project entry never appeared on there, nor on the raw JSON file itself. The project entry still lingers in the Projects UI, and actually also appears in the 'Open from server' dialog. When I try to open it, I get a null exception.

![screen shot 2016-07-20 at 14 20 44](https://cloud.githubusercontent.com/assets/4361140/17003520/37293824-4e85-11e6-9ba9-e58868550e0a.png)

![screen shot 2016-07-20 at 14 20 50](https://cloud.githubusercontent.com/assets/4361140/17003525/39877b94-4e85-11e6-881a-c040717d31c9.png)

**Comment by bdionne** [comment]
seems like a bug, I'll try to reproduce.

The  create project operation actually does go to the server, as it needs to create the history file. When it succeeds, the config is then initialized again, so the button should stay disabled and the new project should show up in the JSON panel.

**Comment by rsgoncalves** [comment]
I tried to reproduce this but currently I can save projects Ok. After adding the first project, the Save button was disabled, though in subsequent project additions the button got enabled. The projects are appearing in the configuration though. (I had been using HTTPS before, now I switched to HTTP).

**Comment by bdionne** [comment]
I think the error handling is also improving things. At some point we're going to add a [separate listener](https://github.com/protegeproject/protege-client/tree/http-metaproject-integration) that will be used for devops. It will enable us to shutdown the web server while the configuration is changed.

**Comment by rsgoncalves** [comment]
With the latest state of the repo I can consistently add projects, but cannot open them. The initial snapshot doesn't seem to be getting flushed out?

```
19:04:54 [XNIO-1 task-11] INFO  - Register root (Root User) to gain server access
19:04:56 [XNIO-1 task-13] INFO  - [Request from UserIdImpl{id=root} (NameImpl{name=Root User}) - Open project] ProjectImpl{id=ProjectIdImpl{id=8a620702-ea61-4a2a-9e70-c7610f48b3c2}, name=NameImpl{name=test2}, description=DescriptionImpl{description=test}, file=root/data/8a620702-ea61-4a2a-9e70-c7610f48b3c2/test2.history, owner=UserIdImpl{id=root}, options=ProjectOptionsImpl{options={}}}
19:04:56 [XNIO-1 task-14] ERROR - root/data/8a620702-ea61-4a2a-9e70-c7610f48b3c2/test2.history-snapshot (No such file or directory)
java.io.FileNotFoundException: root/data/8a620702-ea61-4a2a-9e70-c7610f48b3c2/test2.history-snapshot (No such file or directory)
    at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_74]
    at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_74]
    at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_74]
    at org.protege.editor.owl.server.http.handlers.MetaprojectHandler.handleRequest(MetaprojectHandler.java:260) ~[org.protege.owl.server.jar:na]
    at io.undertow.server.Connectors.executeRootHandler(Connectors.java:198) [org.protege.owl.server.jar:na]
    at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:788) [org.protege.owl.server.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_74]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_74]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
19:04:56 [XNIO-1 task-14] ERROR - UT000034: Stream is closed
java.io.IOException: UT000034: Stream is closed
    at io.undertow.io.UndertowOutputStream.write(UndertowOutputStream.java:116) ~[org.protege.owl.server.jar:na]
    at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877) ~[na:1.8.0_74]
    at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1786) ~[na:1.8.0_74]
    at java.io.ObjectOutputStream.<init>(ObjectOutputStream.java:247) ~[na:1.8.0_74]
    at org.protege.editor.owl.server.http.handlers.MetaprojectHandler.handleRequest(MetaprojectHandler.java:272) ~[org.protege.owl.server.jar:na]
    at io.undertow.server.Connectors.executeRootHandler(Connectors.java:198) [org.protege.owl.server.jar:na]
    at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:788) [org.protege.owl.server.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_74]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_74]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
19:04:56 [XNIO-1 task-14] ERROR - UT005071: Undertow request failed HttpServerExchange{ POST /nci_protege/meta/project/snapshot/get request {Connection=[Keep-Alive], Authorization=[Basic cm9vdDo1Y2Q4MDdjYS0xZTU2LTRlYTMtOTQwZC0yN2E3MjNmMGU4NDE=], Accept-Encoding=[gzip], Content-Length=[471], User-Agent=[okhttp/3.0.0-RC1], Host=[localhost:8080]} response {Connection=[keep-alive], Content-Length=[0], Error-Message=[Server failed to fetch project snapshot], Date=[Fri, 29 Jul 2016 02:04:56 GMT]}}
java.lang.IllegalStateException: UT000002: The response has already been started
    at io.undertow.server.HttpServerExchange.setStatusCode(HttpServerExchange.java:1333) ~[org.protege.owl.server.jar:na]
    at org.protege.editor.owl.server.http.handlers.MetaprojectHandler.internalServerErrorStatusCode(MetaprojectHandler.java:333) ~[org.protege.owl.server.jar:na]
    at org.protege.editor.owl.server.http.handlers.MetaprojectHandler.handleRequest(MetaprojectHandler.java:277) ~[org.protege.owl.server.jar:na]
    at io.undertow.server.Connectors.executeRootHandler(Connectors.java:198) ~[org.protege.owl.server.jar:na]
    at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:788) ~[org.protege.owl.server.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_74]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_74]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_74]
```

**Comment by bdionne** [comment]
Not sure why this [happened](https://github.com/protegeproject/protege-client/commit/915cbe3b4f6b11dced51ad2ea6da0571dd33e78e#diff-2b75f803ca908354e9717fe5dfb2b409L267), it's no longer pushing the snapshot. [This](https://github.com/protegeproject/protege-client/commit/106046eae8dddc0f0a32e66895e41f1884a9d7cc) fixes it. Perhaps it got dropped in all the exception handling rework.
