### ISSUE TITLE
Prompt Diff throws exceptions when asking for the details of commits

### ISSUE THREAD

**Issue by bdionne** [protegeproject/protege-ontology-client#30]
java.util.NoSuchElementException: No value present
    at java.util.Optional.get(Optional.java:135)
    at org.protege.editor.owl.client.diff.model.LogDiff.findBaselineMatches(LogDiff.java:374)
    at org.protege.editor.owl.client.diff.model.LogDiff.initDiff(LogDiff.java:68)
    at org.protege.editor.owl.client.diff.ui.ChangesPanel.updateDiff(ChangesPanel.java:87)
    at org.protege.editor.owl.client.diff.ui.ChangesPanel.access$1(ChangesPanel.java:85)
    at org.protege.editor.owl.client.diff.ui.ChangesPanel$1.statusChanged(ChangesPanel.java:69)
    at org.protege.editor.owl.client.diff.model.LogDiffManager.statusChanged(LogDiffManager.java:168)
    at org.protege.editor.owl.client.diff.model.LogDiffManager.setSelectedCommit(LogDiffManager.java:114)
    at org.protege.editor.owl.client.diff.ui.CommitPanel.lambda$0(CommitPanel.java:47)
    at org.protege.editor.owl.client.diff.ui.CommitPanel$$Lambda$137/1644005383.valueChanged(Unknown Source)
    at javax.swing.JList.fireSelectionValueChanged(JList.java:1796)
    at javax.swing.JList$ListSelectionHandler.valueChanged(JList.java:1810)
    at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
    at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:154)
    at javax.swing.DefaultListSelectionModel.setValueIsAdjusting(DefaultListSelectionModel.java:685)
    at javax.swing.JList.setValueIsAdjusting(JList.java:2140)
    at javax.swing.plaf.basic.BasicListUI$Handler.mouseReleased(BasicListUI.java:2796)
    at javax.swing.plaf.basic.BasicListUI$MouseInputHandler.mouseReleased(BasicListUI.java:1526)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
    at java.awt.Component.processMouseEvent(Component.java:6525)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3322)
    at java.awt.Component.processEvent(Component.java:6290)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4881)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    at java.awt.Container.dispatchEventImpl(Container.java:2278)
    at java.awt.Window.dispatchEventImpl(Window.java:2739)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQu

**Comment by rsgoncalves** [comment]
What steps did you take to produce this?

**Comment by bdionne** [comment]
nothing special. I opened a project that has a healthy number of commits, 15-20 maybe, then started selected them in prompt diff and looking at details. A couple throw this exception.

I'm starting to think #18 is just a refresh issue. After you do a commit, the new commit does show up in the commits panel. When you click the new one, `LogDiff` does a get on the `ChangesbyDate` and comes up empty.

**Comment by rsgoncalves** [comment]
This seems to happen because somehow some annotation changes do not have a property set, which should never happen if the change(s) objects are properly constructed. I haven't been able to reproduce with 20 or so commits, still investigating.

**Comment by bdionne** [comment]
I'll try to run this down today. I suspect maybe `EditTab` is doing something to corrupt data, since the other components are well established. However I just saw it [again](https://gist.github.com/bdionne/dbcd74ad2f9555ca61d0e) testing #18 again and this is using a new ontology with very little history.

**Comment by bdionne** [comment]
I take that back, I haven't seen it in a newer project, the code I added to try and trap it was incorrect. 

I've reliably reproduced this on the older project. I can verify that it is a case where a `Change` has type `Annotation` but the property field is null. The two properties in question are ones where we've been toying with setting ranges for them that are user defined data types, like `def-source-enum`

This might just be an old software error. I can't see anything obvious I'm doing wrong when I add these annotations to annotations in the latest code. I'll close this for now and re-open should it come back.
