### ISSUE TITLE
Error when closing Protege after interacting with the Users view

### ISSUE THREAD

**Issue by johardi** [protegeproject/protege-ontology-client#55]
Steps to reproduce:
1. Login to the server as root user,
2. Go to the "Server Administration" tab,
3. Select one of the user in the 'Users' view (e.g., bob or alice)
4. Close Protege.

This error message will appear (Hint: line 8-10):

```
17:47:24.211 [AWT-EventQueue-0] ERROR o.p.editor.core.ProtegeApplication - Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NullPointerException: null
    at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1577) ~[org.apache.felix.main.jar:na]
    at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1507) ~[org.apache.felix.main.jar:na]
    at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:77) ~[org.apache.felix.main.jar:na]
    at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1993) ~[org.apache.felix.main.jar:na]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_51]
    at org.protege.editor.owl.client.diff.ui.GuiUtils.getIcon(GuiUtils.java:66) ~[classes/:na]
    at org.protege.editor.owl.client.admin.ui.UserListCellRenderer.getListCellRendererComponent(UserListCellRenderer.java:22) ~[classes/:na]
    at org.protege.editor.core.ui.list.MList$MListCellRenderer.getListCellRendererComponent(MList.java:269) ~[classes/:na]
    at javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1361) ~[na:1.8.0_51]
    at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1311) ~[na:1.8.0_51]
    at javax.swing.plaf.basic.BasicListUI.getCellBounds(BasicListUI.java:952) ~[na:1.8.0_51]
    at javax.swing.plaf.basic.BasicListUI$Handler.repaintCellFocus(BasicListUI.java:2807) ~[na:1.8.0_51]
    at javax.swing.plaf.basic.BasicListUI$Handler.focusLost(BasicListUI.java:2823) ~[na:1.8.0_51]
    at javax.swing.plaf.basic.BasicListUI$FocusHandler.focusLost(BasicListUI.java:1577) ~[na:1.8.0_51]
    at com.apple.laf.AquaListUI$FocusHandler.focusLost(AquaListUI.java:103) ~[na:1.8.0_51]
    at java.awt.Component.processFocusEvent(Component.java:6417) ~[na:1.8.0_51]
    at java.awt.Component.processEvent(Component.java:6281) ~[na:1.8.0_51]
    at java.awt.Container.processEvent(Container.java:2234) ~[na:1.8.0_51]
    at java.awt.Component.dispatchEventImpl(Component.java:4881) ~[na:1.8.0_51]
    at java.awt.Container.dispatchEventImpl(Container.java:2292) ~[na:1.8.0_51]
    at java.awt.Component.dispatchEvent(Component.java:4703) ~[na:1.8.0_51]
    at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954) ~[na:1.8.0_51]
    at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:995) ~[na:1.8.0_51]
    at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:661) ~[na:1.8.0_51]
    at java.awt.Component.dispatchEventImpl(Component.java:4752) ~[na:1.8.0_51]
    at java.awt.Container.dispatchEventImpl(Container.java:2292) ~[na:1.8.0_51]
    at java.awt.Component.dispatchEvent(Component.java:4703) ~[na:1.8.0_51]
    at sun.awt.SunToolkit$1.run(SunToolkit.java:518) ~[na:1.8.0_51]
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[na:1.8.0_51]
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) ~[na:1.8.0_51]
    at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_51]
    at java.awt.EventQueue$3.run(EventQueue.java:709) ~[na:1.8.0_51]
    at java.awt.EventQueue$3.run(EventQueue.java:703) ~[na:1.8.0_51]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_51]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[na:1.8.0_51]
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726) ~[na:1.8.0_51]
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_51]
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_51]
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_51]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_51]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_51]
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_51]
17:47:24.218 [AWT-EventQueue-0] ERROR o.p.editor.core.ProtegeApplication - Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NoClassDefFoundError: org/protege/editor/owl/ui/inference/ReasonerProgressUI$1
    at org.protege.editor.owl.ui.inference.ReasonerProgressUI.initWindow(ReasonerProgressUI.java:58) ~[classes/:na]
    at org.protege.editor.owl.ui.inference.ReasonerProgressUI.lambda$reset$255(ReasonerProgressUI.java:151) ~[classes/:na]
    at org.protege.editor.owl.ui.inference.ReasonerProgressUI$$Lambda$115/2097189068.run(Unknown Source) ~[na:na]
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[na:1.8.0_51]
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) ~[na:1.8.0_51]
    at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_51]
    at java.awt.EventQueue$3.run(EventQueue.java:709) ~[na:1.8.0_51]
    at java.awt.EventQueue$3.run(EventQueue.java:703) ~[na:1.8.0_51]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_51]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[na:1.8.0_51]
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726) ~[na:1.8.0_51]
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_51]
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_51]
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_51]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_51]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_51]
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_51]
Caused by: java.lang.ClassNotFoundException: Unable to load class 'org.protege.editor.owl.ui.inference.ReasonerProgressUI$1' because the bundle wiring for org.protege.editor.owl is no longer valid.
    at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1521) ~[org.apache.felix.main.jar:na]
    at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:77) ~[org.apache.felix.main.jar:na]
    at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1993) ~[org.apache.felix.main.jar:na]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_51]
    ... 17 common frames omitted
```

**Comment by bdionne** [comment]
I'm unable to reproduce this, I get:

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "AWT-EventQueue-0"

Seems like an issue with resources not being cleaned up in the right order?

**Comment by rsgoncalves** [comment]
I get the same as Bob. Looking into this.
