### ISSUE TITLE
Unable to pick the output CSV file for exporting search results

### ISSUE THREAD

**Issue by johardi** [protegeproject/protege-ontology-client#58]
Selecting the "Browse" button didn't open the browse file dialog but instead it gave error messages:

```
2016-08-22 15:00:50.875 java[15472:1318674] java.lang.NullPointerException
    at org.protege.editor.core.platform.apple.MacUIUtil.lambda$saveFile$12(MacUIUtil.java:56)
    at org.protege.editor.core.platform.apple.MacUIUtil$$Lambda$136/1625976788.accept(Unknown Source)
    at sun.lwawt.macosx.CFileDialog.queryFilenameFilter(CFileDialog.java:143)
2016-08-22 15:00:50.880 java[15472:1318674] (
    0   CoreFoundation                      0x00007fff8cf5903c __exceptionPreprocess + 172
    1   libobjc.A.dylib                     0x00007fff849f376e objc_exception_throw + 43
    2   CoreFoundation                      0x00007fff8cf58bd9 -[NSException raise] + 9
    3   JavaNativeFoundation                0x0000000126214372 JNFCallBooleanMethod + 211
    4   libawt_lwawt.dylib                  0x00000001293dcdf7 -[CFileDialog askFilenameFilter:] + 88
    5   libawt_lwawt.dylib                  0x00000001293dcd90 -[CFileDialog panel:shouldEnableURL:] + 156
    6   AppKit                              0x00007fff8a90db01 -[NSSavePanel _delegateShouldEnableURL:] + 236
    7   AppKit                              0x00007fff8a90e240 -[NSSavePanel _shouldEnableURL:isDirectoryURLHandler:] + 47
    8   AppKit                              0x00007fff8a90e3c5 -[NSSavePanel fileBrowser:shouldEnableURL:isDirectory:isPackage:] + 109
    9   AppKit                              0x00007fff8abb6326 -[NSNavFinderViewFileBrowser finderView:shouldEnableURL:itemIsContainer:itemIsPackage:] + 96
    10  FinderKit                           0x00007fff8b566f85 -[FIFinderViewGutsController panelDisableNode:] + 166
    11  FinderKit                           0x00007fff8b5663c0 -[FIFinderViewGutsController nodeIsDimmed:] + 348
    12  FinderKit                           0x00007fff8b4e9080 -[FI_TListNameCellView updateTagsImageForNode:selected:] + 81
    13  FinderKit                           0x00007fff8b4f7b10 -[FI_TListViewController outlineView:viewForTableColumn:item:] + 663
    14  AppKit                              0x00007fff8a4160d0 -[NSTableView(NSTableViewViewBased) makeViewForTableColumn:row:] + 76
    15  AppKit                              0x00007fff8a415541 -[NSTableRowData _addViewToRowView:atColumn:row:] + 300
    16  AppKit                              0x00007fff8a41527a -[NSTableRowData _addViewsToRowView:atRow:] + 184
    17  AppKit                              0x00007fff8a4139ad -[NSTableRowData _initializeRowView:atRow:] + 373
    18  AppKit                              0x00007fff8a412ad2 -[NSTableRowData _addRowViewForVisibleRow:withPriorView:] + 396
    19  AppKit                              0x00007fff8a4b29d1 -[NSTableRowData _addRowViewForVisibleRow:withPriorRowIndex:inDictionary:withRowAnimation:] + 254
    20  AppKit                              0x00007fff8a4b27a3 -[NSTableRowData _unsafeUpdateVisibleRowEntries] + 1856
    21  AppKit                              0x00007fff8a4b1fc7 -[NSTableRowData updateVisibleRowViews] + 230
    22  AppKit                              0x00007fff8a4b197d -[NSTableView layout] + 178
    23  FinderKit                           0x00007fff8b501f09 -[FI_TListView layout] + 162
    24  AppKit                              0x00007fff8a4420b4 -[NSView _layoutSubtreeWithOldSize:] + 373
    25  AppKit                              0x00007fff8a442305 -[NSView _layoutSubtreeWithOldSize:] + 966
    26  AppKit                              0x00007fff8a442305 -[NSView _layoutSubtreeWithOldSize:] + 966
    27  AppKit                              0x00007fff8a442305 -[NSView _layoutSubtreeWithOldSize:] + 966
    28  AppKit                              0x00007fff8a442305 -[NSView _layoutSubtreeWithOldSize:] + 966
    29  AppKit                              0x00007fff8a442305 -[NSView _layoutSubtreeWithOldSize:] + 966
    30  AppKit                              0x00007fff8a442305 -[NSView _layoutSubtreeWithOldSize:] + 966
    31  AppKit                              0x00007fff8a442305 -[NSView _layoutSubtreeWithOldSize:] + 966
    32  AppKit                              0x00007fff8a442305 -[NSView _layoutSubtreeWithOldSize:] + 966
    33  AppKit                              0x00007fff8a442305 -[NSView _layoutSubtreeWithOldSize:] + 966
    34  AppKit                              0x00007fff8a442305 -[NSView _layoutSubtreeWithOldSize:] + 966
    35  AppKit                              0x00007fff8a442305 -[NSView _layoutSubtreeWithOldSize:] + 966
    36  AppKit                              0x00007fff8a442305 -[NSView _layoutSubtreeWithOldSize:] + 966
    37  AppKit                              0x00007fff8a442305 -[NSView _layoutSubtreeWithOldSize:] + 966
    38  AppKit                              0x00007fff8a441d60 -[NSView layoutSubtreeIfNeeded] + 885
    39  AppKit                              0x00007fff8a4418ba _NSViewLayoutSubtreesThatUseAutolayoutIfNeeded + 71
    40  AppKit                              0x00007fff8a441841 -[NSWindow(NSConstraintBasedLayout) _layoutViewTree] + 84
    41  AppKit                              0x00007fff8a460d3d -[NSWindow(NSConstraintBasedLayout) layoutIfNeeded] + 246
    42  AppKit                              0x00007fff8a30552e _handleWindowNeedsDisplayOrLayoutOrUpdateConstraints + 612
    43  AppKit                              0x00007fff8aa3b171 __83-[NSWindow _postWindowNeedsDisplayOrLayoutOrUpdateConstraintsUnlessPostingDisabled]_block_invoke1540 + 46
    44  CoreFoundation                      0x00007fff8ce75127 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
    45  CoreFoundation                      0x00007fff8ce75080 __CFRunLoopDoObservers + 368
    46  CoreFoundation                      0x00007fff8ce67188 __CFRunLoopRun + 872
    47  CoreFoundation                      0x00007fff8ce66bd8 CFRunLoopRunSpecific + 296
    48  HIToolbox                           0x00007fff8f0a056f RunCurrentEventLoopInMode + 235
    49  HIToolbox                           0x00007fff8f0a01ee ReceiveNextEventCommon + 179
    50  HIToolbox                           0x00007fff8f0a012b _BlockUntilNextEventMatchingListInModeWithFilter + 71
    51  AppKit                              0x00007fff8a3028ab _DPSNextEvent + 978
    52  AppKit                              0x00007fff8a301e58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
    53  libosxapp.dylib                     0x0000000128e8742a -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 124
    54  AppKit                              0x00007fff8a4cd887 -[NSApplication _realDoModalLoop:peek:] + 666
    55  AppKit                              0x00007fff8a4c9e76 -[NSApplication runModalForWindow:] + 119
    56  AppKit                              0x00007fff8a910a84 -[NSSavePanel runModal] + 323
    57  libawt_lwawt.dylib                  0x00000001293dcf9f -[CFileDialog safeSaveOrLoad] + 391
    58  Foundation                          0x00007fff89847dd0 __NSThreadPerformPerform + 293
    59  CoreFoundation                      0x00007fff8ce75a01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    60  CoreFoundation                      0x00007fff8ce67b8d __CFRunLoopDoSources0 + 269
    61  CoreFoundation                      0x00007fff8ce671bf __CFRunLoopRun + 927
    62  CoreFoundation                      0x00007fff8ce66bd8 CFRunLoopRunSpecific + 296
    63  HIToolbox                           0x00007fff8f0a056f RunCurrentEventLoopInMode + 235
    64  HIToolbox                           0x00007fff8f0a02ea ReceiveNextEventCommon + 431
    65  HIToolbox                           0x00007fff8f0a012b _BlockUntilNextEventMatchingListInModeWithFilter + 71
    66  AppKit                              0x00007fff8a3028ab _DPSNextEvent + 978
    67  AppKit                              0x00007fff8a301e58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
    68  libosxapp.dylib                     0x0000000128e8742a -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 124
    69  AppKit                              0x00007fff8a2f7af3 -[NSApplication run] + 594
    70  libosxapp.dylib                     0x0000000128e8723e +[NSApplicationAWT runAWTLoopWithApp:] + 156
    71  libawt_lwawt.dylib                  0x000000012940a54b -[AWTStarter starter:] + 905
    72  Foundation                          0x00007fff89847dd0 __NSThreadPerformPerform + 293
    73  CoreFoundation                      0x00007fff8ce75a01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    74  CoreFoundation                      0x00007fff8ce67b8d __CFRunLoopDoSources0 + 269
    75  CoreFoundation                      0x00007fff8ce671bf __CFRunLoopRun + 927
    76  CoreFoundation                      0x00007fff8ce66bd8 CFRunLoopRunSpecific + 296
    77  java                                0x0000000109cd2463 CreateExecutionEnvironment + 871
    78  java                                0x0000000109cce1ac JLI_Launch + 1952
    79  java                                0x0000000109cd44c0 main + 101
    80  java                                0x0000000109ccda04 start + 52
)
```

**Comment by johardi** [comment]
Wrong thread, moved to https://github.com/protegeproject/lucene-search-plugin/issues/37
