### ISSUE TITLE
how to use it in protege 5  OR what is the compile command

### ISSUE THREAD

**Issue by upperli** [protegeproject/protege-ontology-client#65]
org.osgi.framework.BundleException: Unresolved constraint in bundle org.protege.editor.owl.client [21]: Unable to resolve 21.0: missing requirement [21.0] osgi.wiring.package; (&(osgi.wiring.package=org.protege.owl.server.api)(version>=3.0.0)(!(version>=4.0.0)))
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4002) ~[org.apache.felix.main.jar:na]
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2045) ~[org.apache.felix.main.jar:na]
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299) ~[org.apache.felix.main.jar:na]
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304) [org.apache.felix.main.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]

**Comment by rsgoncalves** [comment]
This plugin for Protege 5 is not released yet, it is work in progress. To try out the latest client-server you'd have to use the _http-metaproject-integration_ branches of [protege-client](https://github.com/protegeproject/protege-client) and [protege-server](https://github.com/protegeproject/protege-server), and you'll need [metaproject](https://github.com/protegeproject/metaproject) as well. There are readme files in the repositories with instructions on how to build them, but once again, this is not released for Protege 5 yet.
